# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class AgeUnit(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """AgeUnit."""

    YEARS = "years"
    MONTHS = "months"
    DAYS = "days"


class ClinicalDocumentType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ClinicalDocumentType."""

    CONSULTATION = "consultation"
    DISCHARGE_SUMMARY = "dischargeSummary"
    HISTORY_AND_PHYSICAL = "historyAndPhysical"
    PROCEDURE = "procedure"
    PROGRESS = "progress"
    IMAGING = "imaging"
    LABORATORY = "laboratory"
    PATHOLOGY = "pathology"


class ClinicalTrialAcceptedGender(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ClinicalTrialAcceptedGender."""

    FEMALE = "female"
    MALE = "male"


class ClinicalTrialPhase(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ClinicalTrialPhase."""

    NOT_APPLICABLE = "notApplicable"
    EARLY_PHASE1 = "earlyPhase1"
    PHASE1 = "phase1"
    PHASE2 = "phase2"
    PHASE3 = "phase3"
    PHASE4 = "phase4"


class ClinicalTrialPurpose(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ClinicalTrialPurpose."""

    NOT_APPLICABLE = "notApplicable"
    SCREENING = "screening"
    DIAGNOSTIC = "diagnostic"
    PREVENTION = "prevention"
    HEALTH_SERVICES_RESEARCH = "healthServicesResearch"
    TREATMENT = "treatment"
    DEVICE_FEASIBILITY = "deviceFeasibility"
    SUPPORTIVE_CARE = "supportiveCare"
    BASIC_SCIENCE = "basicScience"
    OTHER = "other"


class ClinicalTrialRecruitmentStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ClinicalTrialRecruitmentStatus."""

    UNKNOWN_STATUS = "unknownStatus"
    NOT_YET_RECRUITING = "notYetRecruiting"
    RECRUITING = "recruiting"
    ENROLLING_BY_INVITATION = "enrollingByInvitation"


class ClinicalTrialSource(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ClinicalTrialSource."""

    CUSTOM = "custom"
    CLINICALTRIALS_GOV = "clinicaltrials.gov"


class ClinicalTrialStudyType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """ClinicalTrialStudyType."""

    INTERVENTIONAL = "interventional"
    OBSERVATIONAL = "observational"
    EXPANDED_ACCESS = "expandedAccess"
    PATIENT_REGISTRIES = "patientRegistries"


class DocumentContentSourceType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """DocumentContentSourceType."""

    INLINE = "inline"
    REFERENCE = "reference"


class DocumentType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """DocumentType."""

    NOTE = "note"
    FHIR_BUNDLE = "fhirBundle"
    DICOM = "dicom"
    GENOMIC_SEQUENCING = "genomicSequencing"


class GeoJsonGeometryType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """GeoJsonGeometryType."""

    POINT = "Point"


class GeoJsonPropertiesSubType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """GeoJsonPropertiesSubType."""

    CIRCLE = "Circle"


class GeoJsonType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """GeoJsonType."""

    FEATURE = "Feature"


class JobStatus(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """JobStatus."""

    NOT_STARTED = "notStarted"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    PARTIALLY_COMPLETED = "partiallyCompleted"


class OncoPhenotypeInferenceType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """OncoPhenotypeInferenceType."""

    TUMOR_SITE = "tumorSite"
    HISTOLOGY = "histology"
    CLINICAL_STAGE_T = "clinicalStageT"
    CLINICAL_STAGE_N = "clinicalStageN"
    CLINICAL_STAGE_M = "clinicalStageM"
    PATHOLOGIC_STAGE_T = "pathologicStageT"
    PATHOLOGIC_STAGE_N = "pathologicStageN"
    PATHOLOGIC_STAGE_M = "pathologicStageM"


class PatientInfoGender(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """PatientInfoGender."""

    FEMALE = "female"
    MALE = "male"
    UNSPECIFIED = "unspecified"


class RepeatabilityResult(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """RepeatabilityResult."""

    ACCEPTED = "accepted"
    REJECTED = "rejected"


class TrialMatcherInferenceType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """TrialMatcherInferenceType."""

    TRIAL_ELIGIBILITY = "trialEligibility"
